service: vision-zero-static

provider:
  name: aws
  runtime: nodejs6.10

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  create_viz:
    handler: handler.create_viz

